### ISSUE TITLE
README doesn't mention providing the secret when initializing bogart batteries

### ISSUE THREAD

**Issue by soitgoes** [nrstott/bogart#104]

**Comment by ackalker** [comment]
:+1:

**Comment by ackalker** [comment]
@nrstott Please, my friend, update the `README.md` to get people started.
Perhaps something like:
```js
app.use(bogart.batteries({secret: "my-super-secret"}));
```
I had to clone the Git repo and dig through both `lib` and `examples` (why isn't this included in the npm package?) to figure this out. Not all of us are seasoned jsgi users :smile:

**Comment by nrstott** [comment]
Done

**Comment by ackalker** [comment]
Thanks :)
